name: Build + Deploy Hue Controller

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '6.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: huecontroller
        path: |
          ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output
    - name: Create tag
      if: ${{ github.ref_name == 'main' }}
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/Release-v${{ github.run_number }}',
            sha: context.sha
          })
  deploy:
    if: ${{ needs.build.result=='success' }}
    needs: [build]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/download-artifact@v4.1.7
        with:
          name: huecontroller
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
